### PR TITLE
Create blank.yml

### PR DESCRIPTION
**Pull request by BellaBijl**

### CODE REVIEW

**Comment by BellaBijl** [comment]
I’m just trying my luck

**Review by BellaBijl — COMMENTED** [review]
@@ -0,0 +1,36 @@
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:

**Review by Zmeydimasik — APPROVED** [review]

**Comment by BellaBijl** [comment]
So mote it be blessed

**Comment by BellaBijl** [comment]
💯🤩

**Pull request merged**
